In [1]:
import numpy as np 

A = np.array([[1, 2, 3], [4, 5, 6]]).astype(np.float64)
B = np.array([[7, 8], [9, 10], [11, 12]]).astype(np.float64)
A,B

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]))

## NUMBA Matrix Multiplication

In [2]:
import numba 

@numba.jit(nopython=True)
def matrix_multiply_numba(A, B):
    result = np.zeros((A.shape[0], B.shape[1]))

    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i, j] += A[i, k] * B[k, j]
    return result



## First time NUMBA Function is called

In [3]:
%%time
numba_result = matrix_multiply_numba(A, B)
numba_result

CPU times: user 1.31 s, sys: 1.02 s, total: 2.33 s
Wall time: 585 ms


array([[ 58.,  64.],
       [139., 154.]])

## Second time NUMBA Function is called

In [4]:
%%time
numba_result = matrix_multiply_numba(A, B)
numba_result

CPU times: user 42 µs, sys: 0 ns, total: 42 µs
Wall time: 44.6 µs


array([[ 58.,  64.],
       [139., 154.]])

## Large Matrix Multiplication

In [5]:
# list to collect run-time metrics
# initialize with results for native C implementation
test_results = [
    {"function": "native_c", "duration": 0.009, "results": None}
]

DIM_SIZE = 200
np.random.seed(0)
# Create two random square matrices
A = np.random.rand(DIM_SIZE, DIM_SIZE)
B = np.random.rand(DIM_SIZE, DIM_SIZE)
A.shape, B.shape


((200, 200), (200, 200))

In [6]:
%%time
results = matrix_multiply_numba(A, B)

CPU times: user 10.9 ms, sys: 0 ns, total: 10.9 ms
Wall time: 10.4 ms


## Float 32 inputs

In [7]:
# list to collect run-time metrics
# initialize with results for native C implementation
test_results = [
    {"function": "native_c", "duration": 0.009, "results": None}
]

DIM_SIZE = 250
np.random.seed(1)
# Create two random square matrices
A = np.random.rand(DIM_SIZE, DIM_SIZE).astype(np.float32)
B = np.random.rand(DIM_SIZE, DIM_SIZE).astype(np.float32)
A.shape, B.shape


((250, 250), (250, 250))

In [8]:
%%time
results = matrix_multiply_numba(A, B)

CPU times: user 228 ms, sys: 0 ns, total: 228 ms
Wall time: 226 ms


In [9]:
%%time
results = matrix_multiply_numba(A, B)

CPU times: user 19.2 ms, sys: 0 ns, total: 19.2 ms
Wall time: 18.9 ms
